---
- name: redhat | installing pre-req packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - fping
    - MySQL-python
    - php55-php
    - php55-php-cli
    - php55-php-gmp
    - php55-php-pear
    - php55-php-mysqlnd
    - php55-php-ldap
    - php55-php-mcrypt
    - php55-php-curl
    - wget

- name: redhat | setting php timezone
  lineinfile:
    dest: "/etc/php.ini"
    line: "date.timezone = {{ phpipam_timezone }}"
  notify: restart httpd
